#!/bin/sh
set -eu

npm test
MARKET_NARRATIVE_DEPLOY_TARGET=public \
MARKET_DATA_MODE=mock \
SKIP_DAILY_GENERATE=true \
SKIP_ARCHIVE_WRITE=true \
npm run vercel:build
npm run public:copy:qa -- out/vercel
