ALTER TABLE market_snapshots
    ALTER COLUMN close_value TYPE DOUBLE PRECISION USING close_value::DOUBLE PRECISION,
    ALTER COLUMN change_percent TYPE DOUBLE PRECISION USING change_percent::DOUBLE PRECISION;

ALTER TABLE market_news
    ALTER COLUMN sentiment_score TYPE DOUBLE PRECISION USING sentiment_score::DOUBLE PRECISION,
    ALTER COLUMN entity_match_score TYPE DOUBLE PRECISION USING entity_match_score::DOUBLE PRECISION;

ALTER TABLE narrative_themes
    ALTER COLUMN sentiment_score TYPE DOUBLE PRECISION USING sentiment_score::DOUBLE PRECISION;

ALTER TABLE trade_setups
    ALTER COLUMN entry_price TYPE DOUBLE PRECISION USING entry_price::DOUBLE PRECISION,
    ALTER COLUMN stop_loss TYPE DOUBLE PRECISION USING stop_loss::DOUBLE PRECISION,
    ALTER COLUMN target_price TYPE DOUBLE PRECISION USING target_price::DOUBLE PRECISION,
    ALTER COLUMN risk_reward TYPE DOUBLE PRECISION USING risk_reward::DOUBLE PRECISION;

ALTER TABLE daily_scripts
    ALTER COLUMN overall_sentiment TYPE DOUBLE PRECISION USING overall_sentiment::DOUBLE PRECISION;
