import assert from "node:assert/strict";
import { sourceUrlLooksArticleLevel } from "./news-sources.mjs";
import { DISCLAIMER_MARKER } from "./site-constants.mjs";
const config = {
  publicUrl: envUrl("PUBLIC_URL", "https://www.marketnarrative.in"),
  wwwUrl: envUrl("WWW_URL", "https://www.marketnarrative.in"),
  adminUrl: envUrl("ADMIN_URL", "https://admin.marketnarrative.in"),
  tradeUrl: envUrl("TRADE_URL", "https://trade.marketnarrative.in"),
  authApiUrl: envUrl("AUTH_API_URL", "https://api.marketnarrative.in"),
  tradingApiUrl: envUrl("TRADING_API_URL", "https://trade-api.marketnarrative.in"),
  adminEmail: process.env.TRADING_ADMIN_EMAIL ?? "abhey@marketnarrative.in",
  adminPassword: process.env.TRADING_ADMIN_PASSWORD ?? "",
  nonAdminEmail: process.env.NON_ABHEY_EMAIL ?? "",
  nonAdminPassword: process.env.NON_ABHEY_PASSWORD ?? "",
  authenticated: process.env.RUN_AUTHENTICATED_SMOKE === "true",
  orderBlock: process.env.RUN_ORDER_BLOCK_SMOKE === "true",
  timeoutMs: Number.parseInt(process.env.PROD_SMOKE_TIMEOUT_MS ?? "20000", 10)
};

const results = [];

await check("public apex loads archive", async () => {
  const response = await fetchText(config.publicUrl);
  assert.equal(response.status, 200);
  assert.match(response.body, /Market Narrative|Market Nerve Before The Open|briefings/i);
  assert.doesNotMatch(response.body, /Admin Login|admin\.marketnarrative\.in/i);
  assert.match(response.body, /By Abhey Deep \/ Market Narrative/i);
  assert.match(response.body, /Last updated/i);
  assert.match(response.body, /Search the archive|Join daily email/i);
  assert.match(response.body, /Today's briefing is live|Market closed today|Market holiday|Latest under verification/i);
});

await check("public latest status route is explicit", async () => {
  const response = await fetchText(`${config.publicUrl}/latest/`);
  assert.equal(response.status, 200);
  assert.match(response.body, /Market Narrative latest briefing|No pre-market briefing|briefing was not published as latest/i);
  assert.doesNotMatch(response.body, /Admin Login|admin\.marketnarrative\.in/i);
});

await check("public host serves public deployment target", async () => {
  const payload = await fetchJson(`${config.publicUrl}/deployment-manifest.json`, 200);
  assert.equal(payload.app, "marketnarrative");
  assert.equal(payload.target, "public");
});

await check("public host loads multibagger tracker", async () => {
  const response = await fetchText(`${config.publicUrl}/multibagger/`);
  assert.equal(response.status, 200);
  assert.match(response.body, /Market Narrative Multibagger Portfolio/i);
  assert.match(response.body, /KPEL|DHABRIYA|SHARDAMOTR/i);
  assert.match(response.body, /How to read this page|Research Framework|Investor Discipline|allocation-donut/i);
  assert.doesNotMatch(response.body, /Museum of Fine Arts|MFA Boston|art exhibition/i);
});

await check("public host loads about page", async () => {
  const response = await fetchText(`${config.publicUrl}/about/`);
  assert.equal(response.status, 200);
  assert.match(response.body, /About Market Narrative|Who is Abhey Deep|Methodology/i);
  assert.match(response.body, /I'm Abhey Deep|Browse the archive|verified briefings published since launch/i);
  assert.match(response.body, /aria-current="page">About/i);
  assert.ok(response.body.includes(DISCLAIMER_MARKER));
});

await check("public host loads subscribe page", async () => {
  const response = await fetchText(`${config.publicUrl}/subscribe/`);
  assert.equal(response.status, 200);
  assert.match(response.body, /Subscribe \| Market Narrative|Join daily email/i);
  assert.match(response.body, /method="POST"/i);
  assert.match(response.body, /name="_honey"/i);
  assert.match(response.body, /class="sent-note" hidden/i);
  assert.doesNotMatch(response.body, /Request received\. Check your inbox/i);
  assert.doesNotMatch(response.body, /name="_captcha" value="false"/i);
  assert.match(response.body, /If you do not receive a confirmation email within a few minutes/i);
});

await check("latest public digest exposes verified article sources when generated by the new pipeline", async () => {
  const payload = await fetchJson(`${config.publicUrl}/digest.json`, 200);
  if (!payload.sourceVerification) {
    skip("latest digest source-quality check skipped: legacy archive has no sourceVerification");
    return;
  }
  assert.equal(payload.sourceVerification.blockedReason, null);
  assert.ok(payload.sourceVerification.verifiedArticleCount >= 8);
  assert.ok(payload.sourceVerification.publisherCount >= 1);
  assert.ok(payload.sourceVerification.categoryCount >= 1);
  const selection = payload.publicSourceSelection ?? {};
  if (selection.publishMode === "full_brief") {
    assert.ok(payload.sourceVerification.categoryCount >= 4, "full brief must have broad category coverage");
    assert.ok((selection.directIndiaSourceCount ?? 0) >= 5, "full brief must have at least 5 direct India sources");
    assert.ok((selection.officialIndiaSourceCount ?? 0) >= 3, "full brief must have at least 3 official India sources");
  } else {
    assert.ok(
      ["limited_brief", "global_cue_only", undefined].includes(selection.publishMode),
      `unexpected public publishMode ${selection.publishMode}`
    );
    assert.ok(
      ["limited", "global-cue-only", undefined].includes(selection.evidenceGrade),
      `unexpected public evidenceGrade ${selection.evidenceGrade}`
    );
  }
  assert.ok((payload.news ?? []).every((article) => sourceUrlLooksArticleLevel(article.sourceUrl)), "latest digest has a section homepage source URL");
  assert.equal(JSON.stringify(payload.newsCards ?? []).includes("sentimentScore"), false, "public newsCards leaked raw sentiment scores");
});

await check("latest and previous verified digests do not repeat the same source stack", async () => {
  const payload = await fetchJson(`${config.publicUrl}/archive.json`, 200);
  const verifiedDigests = (payload.digests ?? []).filter((digest) => digest.sourceVerification);
  if (verifiedDigests.length < 2) {
    skip("verified digest overlap check skipped: fewer than two verified archives are published");
    return;
  }
  const [latest, previous] = verifiedDigests;
  assert.ok(latest.sourceVerification.duplicateWithPreviousPercent <= 55);
  const overlap = sourceOverlapPercent(latest.news ?? [], previous.news ?? []);
  assert.ok(overlap <= 55, `headline/source overlap too high: ${overlap}%`);
});

await check("www host loads or redirects cleanly", async () => {
  const response = await fetchText(config.wwwUrl);
  assert.ok([200, 301, 302, 307, 308].includes(response.status), `unexpected status ${response.status}`);
});

await check("www host loads multibagger tracker", async () => {
  const response = await fetchText(`${config.wwwUrl}/multibagger/`);
  assert.ok([200, 301, 302, 307, 308].includes(response.status), `unexpected status ${response.status}`);
  if (response.status === 200) {
    assert.match(response.body, /Market Narrative Multibagger Portfolio/i);
    assert.match(response.body, /Model Holdings|allocation-donut/i);
  }
});

await check("admin host loads script engine login gate", async () => {
  const response = await fetchText(config.adminUrl);
  assert.equal(response.status, 200);
  assert.match(response.body, /Admin Login/i);
  assert.match(response.body, /Studio Command|Private Studio|Daily Reel Script/i);
});

await check("admin host serves admin deployment target", async () => {
  const payload = await fetchJson(`${config.adminUrl}/deployment-manifest.json`, 200);
  assert.equal(payload.app, "marketnarrative");
  assert.equal(payload.target, "admin");
});

await check("admin host loads project components map", async () => {
  const response = await fetchText(`${config.adminUrl}/components/`);
  assert.equal(response.status, 200);
  assert.match(response.body, /Project Components Map|Repository Component Map/i);
  assert.match(response.body, /Admin Login/i);
});

await check("admin host loads multibagger review workflow", async () => {
  const response = await fetchText(`${config.adminUrl}/multibagger/`);
  assert.equal(response.status, 200);
  assert.match(response.body, /Multibagger Review Desk/i);
  assert.match(response.body, /Run Monthly Review/i);
});

await check("trade host loads Abhey login gate", async () => {
  const response = await fetchText(config.tradeUrl);
  assert.equal(response.status, 200);
  assert.match(response.body, /Trading Cockpit/i);
  assert.match(response.body, /Abhey|admin/i);
});

await check("trade host serves trade deployment target", async () => {
  const payload = await fetchJson(`${config.tradeUrl}/deployment-manifest.json`, 200);
  assert.equal(payload.app, "marketnarrative");
  assert.equal(payload.target, "trade");
});

await check("Spring health endpoint is healthy", async () => {
  const payload = await fetchJson(`${config.authApiUrl}/actuator/health`, 200);
  assert.match(String(payload.status ?? ""), /UP|ok/i);
});

await check("FastAPI health endpoint is healthy", async () => {
  const payload = await fetchJson(`${config.tradingApiUrl}/health`, 200);
  assert.equal(payload.status, "ok");
});

await check("trading API rejects unauthenticated access", async () => {
  const response = await fetchText(`${config.tradingApiUrl}/api/market/envelope`);
  assert.equal(response.status, 401);
});

if (config.nonAdminEmail && config.nonAdminPassword) {
  await check("non-Abhey account cannot access trading API", async () => {
    const token = await login(config.nonAdminEmail, config.nonAdminPassword);
    const response = await fetchText(`${config.tradingApiUrl}/api/market/envelope`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    assert.equal(response.status, 403);
  });
} else {
  skip("non-Abhey 403 check skipped: set NON_ABHEY_EMAIL and NON_ABHEY_PASSWORD");
}

if (config.authenticated) {
  if (!config.adminPassword) {
    throw new Error("RUN_AUTHENTICATED_SMOKE=true requires TRADING_ADMIN_PASSWORD");
  }
  const token = await check("Abhey admin can login and receives trade permission", async () => {
    const tokenValue = await login(config.adminEmail, config.adminPassword);
    const claims = decodeJwt(tokenValue);
    assert.equal(String(claims.sub).toLowerCase(), config.adminEmail.toLowerCase());
    assert.equal(claims.role, "ADMIN");
    assert.ok(Array.isArray(claims.permissions));
    assert.ok(claims.permissions.includes("trade:execute"));
    return tokenValue;
  });

  await check("Abhey admin can read trading envelope", async () => {
    const payload = await fetchJson(`${config.tradingApiUrl}/api/market/envelope`, 200, token);
    assert.ok(payload.signals);
    assert.ok(payload.option_chains);
  });

  for (const index of ["NIFTY", "BANKNIFTY"]) {
    await check(`Abhey admin can read ${index} signal`, async () => {
      const payload = await fetchJson(`${config.tradingApiUrl}/api/signals/latest?index=${index}`, 200, token);
      assert.ok(["BUY", "SELL", "WAIT"].includes(payload.action));
      assert.ok(Array.isArray(payload.reasons));
    });
    await check(`Abhey admin can read ${index} option chain`, async () => {
      const payload = await fetchJson(`${config.tradingApiUrl}/api/options/chain?index=${index}`, 200, token);
      assert.equal(payload.index, index);
      assert.ok(Array.isArray(payload.snapshots));
      assert.ok(payload.snapshots.length > 0);
    });
  }

  if (config.orderBlock) {
    await check("order confirmation remains blocked while live orders are disabled", async () => {
      const proposalResponse = await fetchJson(`${config.tradingApiUrl}/api/orders/proposals`, [200, 409], token, {
        method: "POST",
        body: JSON.stringify({ index: "BANKNIFTY" })
      });
      if (proposalResponse.statusCode === 409) {
        assert.match(JSON.stringify(proposalResponse.payload), /WAIT/i);
        return;
      }
      const confirmation = await fetchJson(`${config.tradingApiUrl}/api/orders/confirm`, 200, token, {
        method: "POST",
        body: JSON.stringify({ proposal_id: proposalResponse.payload.proposal_id, manual_confirm: true })
      });
      assert.equal(confirmation.status, "BLOCKED");
      assert.match(JSON.stringify(confirmation.reasons), /ENABLE_LIVE_ORDERS/i);
    });
  } else {
    skip("order block smoke skipped: set RUN_ORDER_BLOCK_SMOKE=true");
  }
} else {
  skip("authenticated Abhey smoke skipped: set RUN_AUTHENTICATED_SMOKE=true and TRADING_ADMIN_PASSWORD");
}

printSummary();

async function check(name, fn) {
  try {
    const value = await fn();
    results.push({ name, status: "PASS" });
    console.log(`PASS ${name}`);
    return value;
  } catch (error) {
    results.push({ name, status: "FAIL", detail: error.message });
    console.error(`FAIL ${name}: ${error.message}`);
    process.exitCode = 1;
    return undefined;
  }
}

function skip(name) {
  results.push({ name, status: "SKIP" });
  console.warn(`SKIP ${name}`);
}

async function login(email, password) {
  const response = await fetchText(`${config.authApiUrl}/api/auth/login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email, password })
  });
  const payload = JSON.parse(response.body || "{}");
  assert.equal(response.status, 200, `login failed with ${response.status}: ${JSON.stringify(payload)}`);
  assert.ok(payload.token, "login response did not include token");
  return payload.token;
}

async function fetchText(url, options = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), config.timeoutMs);
  try {
    const response = await fetch(url, {
      redirect: "follow",
      ...options,
      signal: controller.signal
    });
    return { status: response.status, body: await response.text(), headers: response.headers };
  } catch (error) {
    throw new Error(error.cause?.code ?? error.message);
  } finally {
    clearTimeout(timer);
  }
}

async function fetchJson(url, expectedStatus, token, options = {}) {
  const response = await fetchText(url, {
    method: options.method ?? "GET",
    headers: {
      Accept: "application/json",
      ...(options.body ? { "Content-Type": "application/json" } : {}),
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...(options.headers ?? {})
    },
    body: options.body
  });
  const expected = Array.isArray(expectedStatus) ? expectedStatus : [expectedStatus];
  assert.ok(
    expected.includes(response.status),
    `expected HTTP ${expected.join(" or ")}, got ${response.status}: ${response.body.slice(0, 120).replace(/\s+/g, " ")}`
  );
  const payload = JSON.parse(response.body || "{}");
  if (Array.isArray(expectedStatus)) {
    return { statusCode: response.status, payload };
  }
  return payload;
}

function decodeJwt(token) {
  const [, payload] = token.split(".");
  assert.ok(payload, "token does not contain a payload");
  return JSON.parse(Buffer.from(payload, "base64url").toString("utf8"));
}

function envUrl(name, fallback) {
  return (process.env[name] ?? fallback).replace(/\/$/, "");
}

function sourceOverlapPercent(current, previous) {
  if (!current.length || !previous.length) {
    return 0;
  }
  const previousTitles = new Set(previous.map((article) => normalizeTitle(article.headline ?? article.title)).filter(Boolean));
  const previousUrls = new Set(previous.map((article) => normalizeUrl(article.sourceUrl)).filter(Boolean));
  const overlap = current.filter((article) =>
    previousTitles.has(normalizeTitle(article.headline ?? article.title)) ||
    previousUrls.has(normalizeUrl(article.sourceUrl))
  ).length;
  return Number(((overlap / current.length) * 100).toFixed(1));
}

function normalizeTitle(value) {
  return String(value ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function normalizeUrl(value) {
  try {
    const url = new URL(String(value ?? ""));
    url.hash = "";
    for (const key of ["utm_source", "utm_medium", "utm_campaign", "from"]) {
      url.searchParams.delete(key);
    }
    return url.toString();
  } catch {
    return "";
  }
}

function printSummary() {
  const counts = results.reduce((acc, item) => {
    acc[item.status] = (acc[item.status] ?? 0) + 1;
    return acc;
  }, {});
  console.log(`\nProduction smoke summary: ${counts.PASS ?? 0} passed, ${counts.SKIP ?? 0} skipped, ${counts.FAIL ?? 0} failed.`);
  if (process.exitCode) {
    process.exit(process.exitCode);
  }
}
